#################
#CUSTOM CHALLENGE#
#################

custom_challenge:
  template_id: "custom_challenge"
  display_text: ""
  challenge_type: "custom"
  template_expression: ""
  picks: "[]"


#################
#GAME CHALLENGES
#################

game_turnovers:
  template_id: "game_turnovers"
  display_text: "How many turnovers will occur?"
  challenge_type: "game"
  template_expression: "In the {GAME} game, {PICKS} turnovers will occur."
  picks: "[1,2,3,4,5,6,7,8,9,10]"

game_touchdowns:
  template_id: "game_touchdowns"
  display_text: "How many touchdowns will occur?"
  challenge_type: "game"
  template_expression: "In the {GAME} game, {PICKS} touchdowns will occur."
  picks: "[1,2,3,4,5,6,7,8,9,10]"

game_passing_attempts:
  template_id: "game_passing_attempts"
  display_text: "How many passes will be attempted?"
  challenge_type: "game"
  template_expression: "In the {GAME} game, {PICKS} passes will be attempted."
  picks: "[10,20,30,40,50,60,70,80,90,100]"

game_points:
  template_id: "game_points"
  display_text: "How many points will be scored in total?"
  challenge_type: "game"
  template_expression: "In the {GAME} game, {PICKS} points will be scored in total."
  picks: "[10,20,30,40,50,60,70,80,90,100]"
  
game_rushing_attempts:
  template_id: "game_rushing_attempts"
  display_text: "How many rushing attempts will occur?"
  challenge_type: "game"
  template_expression: "In the {GAME} game, {PICKS} rushing attempts will occur."
  picks: "[10,20,30,40,50,60,70,80,90,100]"
  
game_punts:
  template_id: "game_punts"
  display_text: "How many punts will occur?"
  challenge_type: "game"
  template_expression: "In the {GAME} game, {PICKS} punts will occur."
  picks: "[1,2,3,4,5,6,7,8,9,10]"

game_winner:
  template_id: "game_winner"
  display_text: "Which team will win?"
  challenge_type: "game"
  template_expression: "In the {GAME} game, {PICKS} will be victorious."
  picks: "['home_team_id','away_team_id']"

game_yards:
  template_id: "game_yards"
  display_text: "Which team will gain the most total yards?"
  challenge_type: "game"
  template_expression: "In the {GAME} game, {PICKS} will gain the most total yards."
  picks: "['home_team_id','away_team_id']"
  

#################
#PLAYER CHALLENGES
#################

player_completed_passes:
  template_id: "player_completed_passes"
  display_text: "Which player will throw the most completed passes?"
  challenge_type: "player"
  challenge_subtype: "pvp"
  template_expression: "This week, will {PLAYER} throw the most completed passes?"
  player_filter: "['QB']"
  picks: "[]"

player_rushing_attempts:
  template_id: "player_rushing_attempts"
  display_text: "Which player will rush the most times?"
  challenge_type: "player"
  challenge_subtype: "pvp"
  template_expression: "This week, will {PLAYER} rush the most times?"
  player_filter: "['RB']"
  picks: "[]"
  
player_catches:
  template_id: "player_catches"
  display_text: "Which player will receive the most catches?"
  challenge_type: "player"
  challenge_subtype: "pvp"
  template_expression: "This week, will {PLAYER} receive the most catches?"
  player_filter: "['RB','TE','WR']"
  picks: "[]"

player_yards_after_catch:
  template_id: "player_yards_after_catch"
  display_text: "Which player will have most yards after the catch?"
  challenge_type: "player"
  challenge_subtype: "pvp"
  template_expression: "This week, will {PLAYER} have the most yards after the catch?"
  player_filter: "['RB','TE','WR']"
  picks: "[]"

player_touchdowns:
  template_id: "player_touchdowns"
  display_text: "Which player will score the most touchdowns?"
  challenge_type: "player"
  challenge_subtype: "pvp"
  template_expression: "This week, will {PLAYER} score the most touchdowns?"
  player_filter: "['RB','WR','TE']"
  picks: "[]"
  
player_passing_yards:
  template_id: "player_passing_yards"
  display_text: "Which player will throw for the most yards?"
  challenge_type: "player"
  challenge_subtype: "pvp"
  template_expression: "This week, will {PLAYER} throw for the most yards?"
  player_filter: "['QB']"
  picks: "[]"
  
player_interceptions_thrown:
  template_id: "player_interceptions_thrown"
  display_text: "Which player will throw the most interceptions?"
  challenge_type: "player"
  challenge_subtype: "pvp"
  template_expression: "This week, will {PLAYER} throw the most interceptions?"
  player_filter: "['QB']"
  picks: "[]"  
  
player_fumbles:
  template_id: "player_fumbles"
  display_text: "Which player will fumble the most times?"
  challenge_type: "player"
  challenge_subtype: "pvp"
  template_expression: "This week, will {PLAYER} fumble the most times?"
  player_filter: "['QB','RB']"
  picks: "[]"


  
#################
#TEAM CHALLENGES
#################

team_completed_passes:
  template_id: "team_completed_passes"
  display_text: "Which team will have the most completed passes?"
  challenge_type: "team"
  template_expression: "{TEAM} will have the most completed passes this week."
  
team_turnovers:
  template_id: "team_turnovers"
  display_text: "Which team will have the most turnovers?"
  challenge_type: "team"
  template_expression: "{TEAM} will have the most turnovers this week."

team_touchdowns:
  template_id: "team_touchdowns"
  display_text: "Which team will have the most touchdowns?"
  challenge_type: "team"
  template_expression: "{TEAM} will score the most touchdowns this week."

team_yards:
  template_id: "team_yards"
  display_text: "Which team will have the most total yards?"
  challenge_type: "team"
  template_expression: "{TEAM} will gain the most total yards this week."